services:
  - type: worker  # Измените с "web" на "worker"
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python favor2025.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase:
          name: env
          property: TELEGRAM_BOT_TOKEN
      - key: GOOGLE_CREDENTIALS_JSON
        fromDatabase:
          name: env
          property: GOOGLE_CREDENTIALS_JSON
      - key: CHANNEL_ID
        fromDatabase:
          name: env
          property: CHANNEL_ID
      - key: GOOGLE_SHEETS_KEY
        fromDatabase:
          name: env
          property: GOOGLE_SHEETS_KEY
      - key: ADMIN_PASSWORD
        fromDatabase:
          name: env
          property: ADMIN_PASSWORD
      - key: ALLOWED_ADMIN_IDS
        fromDatabase:
          name: env
          property: ALLOWED_ADMIN_IDS
      - key: ORGANIZER_CONTACT
        fromDatabase:
          name: env
          property: ORGANIZER_CONTACT
    autoDeploy: true
